#!/bin/bash
# This script assumes each user (graphical session) owns one and only one "pulseaudio" process.
# This script only handles xorg (or xwayland) session.
# requires libnotify, pulseaudio

set -eEuo pipefail
trap 's=$?; notify-send -u critical "Failed to execute notify-all."; exit $s' ERR

for p in $(pgrep pulseaudio); do
    dbus=$(grep -z DBUS_SESSION_BUS_ADDRESS /proc/"$p"/environ | tr -d '\0' | sed 's/DBUS_SESSION_BUS_ADDRESS=//')
    user=$(grep -m 1 -z USER /proc/"$p"/environ | tr -d '\0' | sed 's/USER=//')
    dply=$(grep -z DISPLAY /proc/"$p"/environ | tr -d '\0' | sed 's/DISPLAY=//')
    sudo -u "$user" DBUS_SESSION_BUS_ADDRESS="$dbus" DISPLAY="$dply" notify-send "$@"
done
