name: Build Arch Linux packages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pkg: [battery-notifications, cdns, gammastep, libblockdev, networkd-notify, openblas, osmtogeojson, pacfilter, python-mapbox-earcut, swaylock-effects-git, texlive-fontsextra, tun2socks, yacd, yoga-bios-unlock-git]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/actions/makepkg
        with:
          arch: znver2
          pkg: ${{ matrix.pkg }}
      - name: Archive packages
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: pkgs/
  release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/download-artifact@master
        with:
          name: packages
          path: pkgs/
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: ncipollo/release-action@v1.11.1
        with:
          tag: latest
          name: Optimized packages for AMD Zen 2
          omitBody: true
          commit: ${{ github.sha }}
          artifacts: "pkgs/*.pkg.tar.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
