name: Build Arch Linux packages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pkg: [battery-notifications, cdns, networkd-notify-git, pacfilter, python-mapbox-earcut, yacd]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/makepkg
        with:
          arch: znver2
          pkg: ${{ matrix.pkg }}
      - name: Archive packages
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pkg }}
          path: pkgs/
  release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: pkgs/
          merge-multiple: true
      - uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          delete_release: true
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: latest
          name: Optimized packages for AMD Zen 2
          omitBody: true
          commit: ${{ github.sha }}
          artifacts: "pkgs/*"
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
