name: Build Arch Linux packages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/actions/makepkg
        with:
          arch: znver2
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: ncipollo/release-action@v1.9.0
        with:
          tag: latest
          name: Optimized packages for AMD Zen 2
          omitBody: true
          commit: ${{ github.sha }}
          artifacts: "./*/*.pkg.tar.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
